version: '2'

services:
  website:
    container_name: photonix-website
    build: .
    ports:
      - '8880:80'
      - '8001:8001'
      - '8002:8002'
    volumes:
      - ./blog:/srv/blog
      - ./docs:/srv/docs
      - ./docs-theme:/srv/docs-theme
      - ./faqs:/srv/faqs
      - ./geoipdb.mmdb:/srv/geoipdb.mmdb
      - ./mailer:/srv/mailer
      - ./mailinglist:/srv/mailinglist
      - ./mkdocs.yml:/srv/mkdocs.yml
      - ./photonix:/srv/photonix
      - ./project:/srv/project
      - ./static:/srv/static
      - ./system:/srv/system
      - ./templates:/srv/templates
      - ./tests:/srv/tests
      - ./utils:/srv/utils
      - ./test.py:/srv/test.py
      - ./volumes/media:/srv/media
    environment:
      ENV: dev
      POSTGRES_DB: photonix_website
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      # MATOMO_BASE_URL: http://matomo/
      # MATOMO_SITE_ID: 1
      # MATOMO_TOKEN_AUTH: 38506f6771744c2a8e2398f513d0ccc0
      CELERY_BROKER_URL: redis://redis:6379/0
      EMAIL_HOST: mail.epixstudios.co.uk
      EMAIL_PORT: 587
      EMAIL_HOST_USER: damian@epixstudios.co.uk
      EMAIL_HOST_PASSWORD: E5nFMJtxrZLvYneFzG

  postgres:
    container_name: photonix-website-postgres
    image: postgres:12.2-alpine
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_DB: photonix_website
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    container_name: photonix-website-redis
    image: redis:6.2.2
    ports:
      - '6379:6379'

  # matomo-mysql:
  #   container_name: matomo-mysql
  #   image: mysql:5.7
  #   volumes:
  #    - ./volumes/mysql:/var/lib/mysql
  #   ports:
  #    - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: matomo

  # matomo:
  #   container_name: matomo
  #   image: matomo:4.1.1-apache
  #   ports:
  #    - "8008:80"
  #   environment:
  #     MATOMO_DATABASE_HOST: matomo-mysql
  #     MATOMO_DATABASE_USERNAME: root
  #     MATOMO_DATABASE_PASSWORD: password
  #     MATOMO_DATABASE_DBNAME: matomo
  #   links:
  #     - matomo-mysql
  #   volumes:
  #     - ./volumes/matomo/config:/var/www/html/config
