site_name: Photonix Documentation
theme:
  name: readthedocs
  custom_dir: docs-theme/
nav:
    - Home: 'index.md'
    - Configuration: 'configuration.md'
    - Users and Libraries: 'users_libraries.md'
    - Upgrading: 'upgrading.md'
    - Reverse Proxies: 'reverse_proxies.md'
    - Sustainability: 'sustainability.md'
    - Developer:
      - Home: 'developer/index.md'
      - Frontend: 'developer/frontend.md'
      - Adding or Upgrading JS Packages: 'developer/adding_upgrading_js_packages.md'
      - Image Analysis: 'developer/image_analysis.md'
      - Building for Production: 'developer/building.md'
