site_name: Photonix Documentation
theme:
  name: readthedocs
  custom_dir: docs-theme/
nav:
    - Home: 'index.md'
    - Configuration: 'configuration.md'
    - Upgrading: 'upgrading.md'
    - Reverse Proxies: 'reverse_proxies.md'
    - Developer:
      - Home: 'developer/index.md'
      - Frontend: 'developer/frontend.md'
      - Adding or Upgrading JS Packages: 'developer/adding_upgrading_js_packages.md'
      - AI Models: 'developer/ai_models.md'
      - Building Tensorflow: 'developer/building_tensorflow.md'
